databases:
  - name: slacktosms
    databaseName: slacktosms
    user: slacktosms
    plan: basic-256mb

services:
  - type: web
    name: slacktosms
    runtime: ruby
    plan: starter
    buildCommand: "./bin/render-build.sh"
    # preDeployCommand: "bundle exec rails db:migrate" # preDeployCommand only available on paid instance types
    startCommand: "bundle exec rails server"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: slacktosms
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false
      - key: WEB_CONCURRENCY
        value: 2 # sensible default
  - type: worker
    name: slacktosms_worker
    runtime: ruby
    plan: starter
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec good_job start"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: slacktosms
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false